image: gradle:4.8.0-jdk8

stages:
    - build
    - test

job1:
    stage: build
    script: gradle clean assemble

job2:
    stage: test
    script: gradle clean test
    only:
        - master@Redrield/SaturnShell
